collections:
  /:
    permalink: /{slug}/
    template: index
    filter: "tag:blog"
  /store/:
    permalink: /gallery/{slug}/
    template: gallery
    filter: "tag:gallery"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
