collections:
  /:
    permalink: /{slug}/
    template: index
    filter: "tag:blog"
  /gallery/:
    permalink: /gallery/{slug}/
    template: gallery
    data: tag.gallery
    filter: "tag:gallery"
  /abecedaria/:
    permalink: /abecedaria/{slug}/
    template: gallery
    data: tag.abecedarium
    filter: "tag:abecedarium"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
